### PR TITLE
[Merged by Bors] - Fix mac compile csv_reader failure

### PR DESCRIPTION
**Pull request by shiyingjin**
Signed-off-by: jinshiying <jin.shiying@zte.com.cn>

### CODE REVIEW

**Comment by EFanZh** [comment]
I expect this to be merged after https://github.com/actions/virtual-environments/issues/812 being fixed.

**Comment by EFanZh** [comment]
bors retry

**Comment by EFanZh** [comment]
bors retry

**Comment by amadeus-zte** [comment]
bors retry

**Pull request closed without merging**
